build:
  main: main.go
  id: "env-utils-go"
  binary: env-utils
  builder: go
  ldflags: -s -w -X github.com/outline-insurance/env-utils/main/version.Version={{.Tag}}
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - '386'
    - arm64

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
    
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
