on:
  push:
    # only run when new tag is created
    tags:
      - '*'
  
name: Release Env-Utils

jobs:
    build_and_release:
        name: Build and Release
        runs-on: [ubuntu-latest]
        timeout-minutes: 15

        steps:
        - name: Checkout
          # From: https://github.com/actions/checkout
          uses: actions/checkout@v2
          # needed for gorealease action to function correctly
          with:
            fetch-depth: 0

        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version: '1.18'

        - name: Import GPG key
          id: import_gpg
          uses: crazy-max/ghaction-import-gpg@v5
          with:
            gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
            passphrase: ${{ secrets.GPG_PASSPHRASE }}

        - name: Run GoReleaser
          # From: https://github.com/marketplace/actions/goreleaser-action
          uses: goreleaser/goreleaser-action@v2
          with:
            distribution: goreleaser
            version: v3.0.0
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
