on:
  pull_request
  
name: Build and test env-utils

jobs:
    build_and_test:
        name: build and test
        runs-on: [ubuntu-latest]
        timeout-minutes: 15

        steps:
        - name: Checkout
          # From: https://github.com/actions/checkout
          uses: actions/checkout@v2
        
        - name: Checkout Production
          # From: https://github.com/actions/checkout
          uses: actions/checkout@v2
          with:
            ref: production
            path: production
        
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: '1.18'

        - name: Build and Test
          id: build 
          env:
            GIT_SHA: ${{ github.sha }}
          run: |
            echo "building package"
            go install .
            go build
            echo "package built"
            echo "running go tests"
            go test -v ./...
            echo "testing command line functionality"

            # Test secret functionality.
            ./env-utils secret populate "sample/secret.jsonc" -r "us-east-2"
            ./diff_test.sh .secret_env sample/.secret_env
            
            ./env-utils secret populate -l "sample/secret.jsonc" -r "us-east-2"
            ./diff_test.sh .secret_env sample/.secret_env_local

            # Test non-secret functionality.
            ./env-utils non-secret populate "sample/non-secret.jsonc"
            ./diff_test.sh .non_secret_env sample/.non_secret_env
            
            ./env-utils non-secret populate -l "sample/non-secret.jsonc"
            ./diff_test.sh .non_secret_env sample/.non_secret_env_local

            echo "finished testing command line functionality"

            echo "testing that version file is updated"
            ./version.sh version.txt production/version.txt
