on:
    pull_request:
  
name: Build and test env-utils

jobs:
    build_and_test:
        name: build and test
        runs-on: [ubuntu-latest]
        timeout-minutes: 15

        steps:
        - name: Checkout
          # From: https://github.com/actions/checkout
          uses: actions/checkout@v2
        
        - name: Configure DEV AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2

        - name: Build and Test 
          run: |
            # need to make sure that we package the node modules with the lambdas
            echo "building package"
            go install .
            go build
            echo "package built"
            echo "running go tests"
            go test -v ./...
            echo "testing command line functionality"
            env-utils secret populate "sample/secret.jsonc" -r "us-east-2"
            ./diff_test.sh .secret_env sample/.secret_env
            